# -*- coding: utf-8 -*-
"""ML_project_DININGCODE.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uI1gIXrE1U50FoqZUDmz8CIBqdtWet74

다이닝 코드 음식장소 추천
"""

# ChromeDriver 설치
!apt-get update
!apt-get install -y chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

!pip install webdriver_manager
!pip install --upgrade webdriver_manager
!pip install threadpoolctl==3.1.0

# Selenium 설치
!pip install selenium
!pip install --upgrade selenium

import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from urllib.request import urlopen
from selenium import webdriver
import re
import time
import urllib
import requests
from selenium import webdriver
from selenium.webdriver.chrome.options import Options


# Chrome 옵션 설정
chrome_options = Options()
chrome_options.add_argument('--headless')  # 브라우저를 표시하지 않고 실행할 경우

chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

"""구별로 링크 가져오기

https://www.diningcode.com/?region=

https://www.diningcode.com/profile.php?rid=
"""

#서울시 구 정의 : 총 24개의 구
gu_list = ["강남구","강동구","강북구","강서구","관악구","광진구","구로구","금천구",
          "노원구","도봉구","동대문구","동작구","마포구","서대문구","서초구","성북구",
           "송파구","양천구","영등포구","용산구","은평구","종로구","중구", "중랑구"]

# 다이닝 코드에서 식당 링크 가져오기
def get_links_DiningCode(gu):
    # Chrome 옵션 설정
    chrome_options = Options()
    chrome_options.add_argument('--headless')  # 브라우저를 표시하지 않고 실행할 경우
    chrome_options.add_argument('--no-sandbox')
    chrome_options.add_argument('--disable-dev-shm-usage')

    # Chrome 드라이버 초기화
    driver = webdriver.Chrome(options=chrome_options)

    # 올바른 도시 코드 및 인코딩을 사용하여 URL 수정
    encoded_gu = urllib.parse.quote(gu)  # 한글 문자를 URL에 사용하기 위해 인코딩
    url = f"https://www.diningcode.com/list.php?query=서울%20{encoded_gu}"

    print("접근 중인 URL:", url)  # 이 줄을 추가하여 접근 중인 URL을 출력

    # 사용자 에이전트 헤더 설정
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'
    }

    # HTTP GET 요청 보내기
    response = requests.get(url, headers=headers)

    # 로딩된 후 모든 링크 찾기
    link_elements = driver.find_elements(By.TAG_NAME, "a")
    res_links_raw = [link.get_attribute('href') for link in link_elements]

    res_links = [link for link in res_links_raw if 'profile' in link]
    res_links = list(set(res_links))
    Diningcode_links.extend(res_links)
    print(f'{gu}에서 {len(res_links)}곳 찾음')

    # 데이터가 충분하지 않은 경우
    if len(res_links) < 80:
        retry.append(gu)

    driver.close()

Diningcode_links = []
retry = []

for gu in gu_list:
    get_links_DiningCode(gu)

for gu in retry:
    get_links_DiningCode(gu)

len(Diningcode_links)

Diningcode_links = list(set(Diningcode_links))

# save into text
with open("/content/drive/MyDrive/ML_data/restaurants_DiningCode.txt","w") as f:
    f.write('\n'.join(Diningcode_links))

"""크롤링
리뷰 & 가게
"""

D_restaurants_df = pd.DataFrame(columns=['name', 'address', 'category', 'main_mn', 'price', 'opng_tm', 'rating', 'rvw_cnt', 'tags'])
D_review_df = pd.DataFrame(columns=['res_name', 'user_name', 'rating', 'review'])

with open("/content/drive/MyDrive/ML_data/restaurants_DiningCode.txt", "r") as f:
    text = f.read()
urls = text.split()
urls

def crawling_reviews_DiningCode(name, link, driver):
    reviews = pd.DataFrame(columns=['res_name','user_name','rating','review'])
    try:
        driver.get(link)
    except:
        return None

    while True:
        try:
            click_more = driver.find_element_by_xpath("""//*[@id="div_more_review"]""")
            click_more.click()
        except:
            break

    time.sleep(1)

    try:
        html = driver.page_source
        soup = BeautifulSoup(html, 'html.parser')

        for user in soup.find('div',{'id':'div_review'}).find_all('div',{'id':re.compile('div_review_+')}):
            tmp = user.find('span','btxt').get_text()
            user_name = tmp[:tmp.find('(')].strip()
            user_rating = int(re.findall('\d+',user.find('i',{'style':re.compile('width:+')})['style'])[0])//20
            user_review = user.find('p','review_contents btxt').get_text().replace('\n','')

            reviews = reviews.append({'res_name':name,
                                    'user_name':user_name,
                                    'rating':user_rating,
                                    'review':user_review}, ignore_index=True)
    except:
        return None

    return reviews

D_restaurants_df
D_review_df

def crawling_res_data_DiningCode(link, driver):
    try:
        # Chrome 드라이버를 사용하여 링크 불러오기
        driver.get(link)

        # 페이지 로딩을 기다림 (예: 10초 동안 대기)
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.CLASS_NAME, 'tit'))
        )
    except Exception as e:
        print('링크 에러:', link)
        print(e)
        return None, None, None, None, None, None, None, None, None, None

    # 상호명
    try:
        name = driver.find_elements_by_class_name('tit')[3].text
        print(name)
    except:
        name = None

    # 주소
    try:
        address = driver.find_element_by_class_name('locat').text
    except:
        address = None

    # 업종(다이닝코드엔 업종이 없음)
    category = None

    # 주메뉴
    try:
        main_menu = driver.find_element_by_css_selector('div.menu-info.short p.l-txt').text.strip()
    except:
        main_menu = None

    # 가격(주메뉴)
    try:
        price = int(driver.find_element_by_css_selector('div.menu-info.short p.r-txt').text[:-1].replace(',', ''))
    except:
        price = None

    # 영업시간
    try:
        time_dict = dict()
        opening_time_list = driver.find_elements_by_css_selector('div.busi-hours.short p')[1:]
        for i in range(len(opening_time_list))[0::2]:
            if opening_time_list[i].text != '더보기':
                time_dict[opening_time_list[i].text] = opening_time_list[i+1].text

        opening_time = str(time_dict)
    except:
        opening_time = None

    # 평점과 리뷰 수
    try:
        ratings = float(driver.find_element_by_css_selector('strong.rate-point span').text)
        tmp = ratings[0].text.strip()
        rating = float(ratings[1].text[:-1])
        review_count = tmp[:tmp.find('명')]
    except:
        rating = None
        review_count = None

    # 태그
    try:
        tags = ','.join([i.text[:i.text.find('(')] for i in driver.find_elements_by_css_selector('p.icon')])
    except:
        tags = None

    # 리뷰 데이터 가져오기
    res_reviews = crawling_reviews_DiningCode(name, link, driver)

    return name, address, category, main_menu, price, opening_time, rating, review_count, tags, res_reviews

count = 1
for url in urls:
    try:

        chrome_path = '/usr/lib/chromium-browser/chromedriver.exe'
        driver = webdriver.Chrome(options=chrome_options)

        print(count, '\t|', end='')

        name, address, category, main_menu, price, opening_time, rating, review_count, tags, review_df = crawling_res_data_DiningCode(url, driver)

        D_restaurants_df = D_restaurants_df.append({
            'name': name,
            'address': address,
            'category': category,
            'main_mn': main_menu,
            'price': price,
            'opng_tm': opening_time,
            'rating': rating,
            'rvw_cnt': review_count,
            'tags': tags
        }, ignore_index=True)

        D_review_df = D_review_df.append(review_df, ignore_index=True)

        count += 1
    finally:
        if 'driver' in locals():
            driver.quit()

D_restaurants_df.to_csv('/content/drive/MyDrive/ML_data/DiningCode_df.csv', index=False)
D_review_df.to_csv('/content/drive/MyDrive/ML_data/DiningCode_review_df.csv', index=False)

"""
LabelEncoder를 사용하여 식당 이름과 사용자 이름을 숫자 값으로 변환

문장부호 제거

번역 후 라벨 추가"""

!pip install pypapago

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tqdm.notebook import tqdm
from pypapago import Translator

# Load DiningCode data
eat_info = pd.read_csv("/content/drive/MyDrive/ML_data/DiningCode_df.csv")
eat_review = pd.read_csv("/content/drive/MyDrive/ML_data/DiningCode_review_df.csv")

eat_info.head()

eat_review.head()

# Drop NaN values
eat_info = eat_info[eat_info['name'].notnull()]
eat_review = eat_review[eat_review['user_name'].notnull()]

# Reset index
eat_info.reset_index(drop=True, inplace=True)
eat_review.reset_index(drop=True, inplace=True)

# Delete overlapped data
# 식당 정보 데이터 세트에서 중복 제거. 중복은 식당 이름 기준
for id in eat_info.index:
    if list(eat_info['name']).count(eat_info.loc[id, 'name']) > 1:
        eat_info.drop(id, inplace=True)

# Label encoding, Place_name -> p_id, User_name -> u_id
# LabelEncoder를 사용하여 식당 이름과 사용자 이름을 숫자 값으로 변환
# (p_id는 place_id 및 u_id는 user_id로) 인코딩
le = LabelEncoder()
le.fit(eat_info['name'])
eat_info['p_id'] = le.transform(eat_info['name'])
eat_review['p_id'] = le.transform(eat_review['res_name'])

user_le = LabelEncoder()
user_le.fit(eat_review['user_name'])
eat_review['u_id'] = user_le.transform(eat_review['user_name'])

# Delete punctuation marks
# 리뷰에서 문장 부호 제거
def delete_punctuation_marks_review(review):
    review = review.replace('.', '. ')
    review = review.replace('!', '! ')
    review = review.replace('(', '( ')
    review = review.replace(')', ') ')
    review = review.replace('^', '')
    review = review.replace('*', '')
    review = review.replace('-', ' ')
    review = review.replace('\n', '. ')
    review = review.replace('\"', '. ')
    return review

eat_info.head()

eat_review.head()

eat_info['reviews'] = ''

ts = Translator()
eat_review['review_eng'] = ''

eat_info.head()

eat_review.head()

!pip uninstall googletrans

!pip install googletrans==4.0.0-rc1

from tqdm import tqdm
from googletrans import Translator
import pandas as pd

# 리뷰 번역 함수
def translate_review(review):
    try:
        translator = Translator()
        translated_review = translator.translate(review, src='ko', dest='en').text
        return translated_review
    except Exception as e:
        print(f"번역 오류: {e}")
        return ''

# 리뷰 번역 및 결과 출력
for id in tqdm(eat_review.index):
    review = eat_review.loc[id, 'review']

    if pd.isnull(review):
        continue

    # 리뷰가 이미 번역되었는지 확인
    if pd.isnull(eat_review.loc[id, 'review_eng']):
        review_pre = delete_punctuation_marks_review(review)
        review_ts = translate_review(review_pre)

        eat_review.loc[id, 'review_eng'] = review_ts
        print(f"원본: {review}, 번역: {review_ts}")

# 각 레스토랑에 대한 번역된 리뷰 수집
for id in eat_info['p_id']:
    review_all = ''

    for review in eat_review[eat_review['p_id'] == id]['review_eng']:
        if isinstance(review, str):
            review_all += review + '. '
        elif isinstance(review, float):
            review_all += str(review) + '. '

    eat_info.loc[eat_info['p_id'] == id, 'reviews'] = review_all

eat_info.head()

eat_review.head()

# Save to CSV
eat_info.to_csv('/content/drive/MyDrive/ML_data/translated_eat_info.csv', index=False)
eat_review.to_csv('/content/drive/MyDrive/ML_data/translated_eat_review.csv', index=False)

"""prevent unnecessary API calls for already translated reviews"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tqdm.notebook import tqdm

from tqdm import tqdm
from googletrans import Translator

# DiningCode 데이터 로드
eat_info = pd.read_csv("/content/drive/MyDrive/ML_data/translated_eat_info.csv")
eat_review = pd.read_csv("/content/drive/MyDrive/ML_data/translated_eat_review.csv")

# 리뷰 번역 함수
def translate_review(review):
    try:
        translator = Translator()
        translated_review = translator.translate(review, src='ko', dest='en').text
        return translated_review
    except Exception as e:
        print(f"번역 오류: {e}")
        return ''

# 리뷰 번역 및 결과 출력
for id in tqdm(eat_review.index):
    review = eat_review.loc[id, 'review']

    if pd.isnull(review):
        continue

    # 리뷰가 이미 번역되었는지 확인
    if pd.isnull(eat_review.loc[id, 'review_eng']):
        review_pre = delete_punctuation_marks_review(review)
        review_ts = translate_review(review_pre)

        eat_review.loc[id, 'review_eng'] = review_ts
        print(f"원본: {review}, 번역: {review_ts}")

# 각 레스토랑에 대한 번역된 리뷰 수집
for id in eat_info['p_id']:
    review_all = ''

    for review in eat_review[eat_review['p_id'] == id]['review_eng']:
        if isinstance(review, str):
            review_all += review + '. '
        elif isinstance(review, float):
            review_all += str(review) + '. '

    eat_info.loc[eat_info['p_id'] == id, 'reviews'] = review_all

# CSV로 저장
eat_info.to_csv('/content/drive/MyDrive/ML_data/translated_eat_info.csv', index=False)
eat_review.to_csv('/content/drive/MyDrive/ML_data/translated_eat_review.csv', index=False)

"""음식 정보와 사용자 리뷰 데이터

태그 기반으로 KMeans 클러스터링

->  res_matrix와 user_matrix 데이터프레임을 생성
"""

import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from gensim import models
from gensim.models import KeyedVectors
from sklearn.cluster import KMeans
from tqdm.notebook import tqdm

from collections import Counter

def delete_punctuation_marks_tag(word):
    word = word.replace(",","")
    word = word.replace(".","")
    word = word.replace(",","")
    word = word.replace("!","")
    word = word.replace(":","")
    word = word.replace("?","")
    word = word.replace("~","")
    word = word.replace("\\","")
    word = word.replace("\"","")
    word = word.replace(";","")
    return word.lower()

eat_info = pd.read_csv('/content/drive/MyDrive/ML_data/translated_eat_info.csv')
eat_review = pd.read_csv('/content/drive/MyDrive/ML_data/translated_eat_review.csv')

eat_review_by_user = pd.DataFrame(index = eat_review['u_id'].unique(), columns=['reviews'])

for id in tqdm(eat_review['u_id'].unique()):
    review_all = ''
    for review in eat_review.loc[eat_review['u_id']==id,'review_eng']:
        if type(review) != float:
            review_all += review+'. '
    eat_review_by_user.loc[id,'reviews'] = review_all

eat_info['tags']=''
eat_review_by_user['tags']=''

eat_info.head()

eat_review_by_user.head()

with open('/content/drive/MyDrive/ML_data/stop_words.txt','r',-1,'utf-8') as f:
    stop_words = set(f.read().split('/'))

stop_words

def get_tags_to_txt(text):
    if type(text) != str:
        return ''
    text = word_tokenize(text)
    tags_dump = nltk.pos_tag(text)
    tags = []

    for word in tags_dump:
        if (word[1] == 'JJ') and (word[0] not in stop_words):
            tags.append(delete_punctuation_marks_tag(word[0]))

    tags = ','.join(tags)

    return tags

import nltk
nltk.download('averaged_perceptron_tagger', quiet=True)

for i in tqdm(eat_info.index):
    eat_info.loc[i,'tags'] = get_tags_to_txt(eat_info.loc[i,'reviews'])

for i in tqdm(eat_review_by_user.index):
    eat_review_by_user.loc[i,'tags'] = get_tags_to_txt(eat_review_by_user.loc[i,'reviews'])

"""word2vec model :

https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?resourcekey=0-wjGZdNAUop6WykTtMip30g

Word2Vec을 사용하여 앞선 tokenizing 단계에서 추출해낸 형용사를 300차원의 벡터로 변형한 후,

K-means 알고리즘을 사용해 클러스터링 작업을 수행
"""

import gensim
from gensim.models import KeyedVectors
import gzip

# Path to the compressed file
file_path_gz = "/content/drive/MyDrive/ML_data/GoogleNews-vectors-negative300.bin.gz"

# Path to save the extracted bin file
file_path_bin = "/content/drive/MyDrive/ML_data/GoogleNews-vectors-negative300.bin"

# Extract the compressed gzip file
with gzip.open(file_path_gz, 'rb') as f_in, open(file_path_bin, 'wb') as f_out:
    f_out.writelines(f_in)

# Load the Word2Vec model
w2v = KeyedVectors.load_word2vec_format(file_path_bin, binary=True)
print("Word2Vec model loaded successfully.")

print("Word2Vec 모델의 어휘 크기:", len(w2v.key_to_index))
print("Word2Vec 모델의 어휘:", list(w2v.key_to_index.keys()))

All_tags = set()
for tags in eat_info['tags']:
    All_tags.update(set(tags.split(',')))

new_df = pd.DataFrame()
for word in All_tags:
    try:
        f_vec = w2v.get_vector(word)
        new_df[word] = f_vec
    except:
        pass

# new_df 출력
print(new_df)

x = new_df.T
cluster_count=120
model = KMeans(n_clusters=cluster_count)
model.fit(x)
model.predict(x)
Y=x.copy()
Y['kmeans_id'] = model.predict(x)

km = list(Y['kmeans_id'])
max_count = 0
max_count_id = ''
for i in range (0, cluster_count):
    if km.count(i) > max_count:
        max_count = km.count(i);
        max_count_id = i;
    print(i,': ', km.count(i))
max_count_id

km_df = pd.DataFrame()
km_df['group_'+str(max_count_id)] = pd.Series(list(Y[Y['kmeans_id'] == max_count_id].index))
for i in range(0, cluster_count):
    col_name = 'group_'+str(i)
    words = list(Y[Y['kmeans_id'] == i].index)
    km_df[col_name] = pd.Series(words)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
km_df.fillna(0)

# remove groups we don't need
# rm_groups = [17, 26, 50, 63]
# for i in rm_groups:
#     group_name = 'group_'+str(i);
#     stop_words.update(set(km_df[group_name].dropna()))
# with open('../data/stop_words.txt','w',-1,'utf-8') as f:
#     f.write('/'.join(stop_words))
eat_info.set_index(eat_info['p_id'],inplace=True,drop=True)
del eat_info['p_id']
eat_info.head()

res_matrix = pd.DataFrame(index=eat_info.index,columns=list(km_df.columns))
user_matrix = pd.DataFrame(index=eat_review_by_user.index,columns=list(km_df.columns))
res_matrix = res_matrix.fillna(0)
user_matrix = user_matrix.fillna(0)

res_matrix.head()

user_matrix.head()

for id in tqdm(res_matrix.index):
    tags = Counter(eat_info.loc[id,'tags'].split(','))
    for tag in tags.keys():
        for num in range(0,cluster_count):
            if tag in set(km_df['group_'+str(num)]):
                res_matrix.loc[id,'group_'+str(num)] += tags[tag]

res_matrix.head()

for id in tqdm(user_matrix.index):
    tags = Counter(eat_review_by_user.loc[id,'tags'].split(','))
    for tag in tags.keys():
        for num in range(0,cluster_count):
            if tag in set(km_df['group_'+str(num)]):
                user_matrix.loc[id,'group_'+str(num)] += tags[tag]

user_matrix.head()

user_matrix.head()

km_df.count()

eat_review_score = pd.DataFrame(eat_review, columns=['u_id','p_id','rating'])
eat_review_score.sort_values(by=['u_id'], axis=0,inplace=True)
eat_review_score.reset_index(drop = True, inplace=True)
eat_review_score.head()

res_matrix.to_csv('/content/drive/MyDrive/ML_data/res_matrix.csv')
user_matrix.to_csv('/content/drive/MyDrive/ML_data/user_matrix.csv')

eat_review_score.to_csv('/content/drive/MyDrive/ML_data/score_board.csv',index=False)

# 클러스터링 결과
km_df.to_csv('/content/drive/MyDrive/ML_data/eat_cluster.csv',index=False)

km_df.count().to_csv('/content/drive/MyDrive/ML_data/group_count.csv')

"""NCF 모델"""

!pip install cornac

import pandas as pd
import numpy as np
import tensorflow as tf
import cornac
import cornac.eval_methods
from cornac.eval_methods import RatioSplit, base_method
from cornac.hyperopt import Continuous, Discrete, RandomSearch
from tqdm import tqdm

import warnings
warnings.filterwarnings(action='ignore')
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

# 추천할 top k개의 장소
TOP_K = 10
data_df = pd.read_csv('/content/drive/MyDrive/ML_data/score_board (1).csv', index_col =0)
data_df['rating'] =data_df['rating'].astype('float')

# # 'u_id'를 열로 변환
# data_df.reset_index(inplace=True)

# 데이터가 잘 처리되었는지 확인
print(data_df)

data_df = data_df.rename({'u_id': 'userID', 'p_id': 'itemID'}, axis=1)

print(data_df.head())

data = [tuple(x) for x in data_df.values]
data

# Instantiate evaluation metrics
ndcg = cornac.metrics.NDCG(k=TOP_K)
pre = cornac.metrics.Precision(k=TOP_K)
rec = cornac.metrics.Recall(k=TOP_K)
fm = cornac.metrics.FMeasure(k=TOP_K)

# Assuming data is a list of records
for record in data:
    print(record)

#Define an evaluation method to split feedback into train and test sets
ratio_split = RatioSplit(
    data=data,
    test_size=0.1,
    val_size=0.1,
    rating_threshold=1.0,
    seed=123,
    verbose=True,
)

neumf = cornac.models.NeuMF(
    layers=[64, 32, 16, 8],
    act_fn="tanh",
    learner="adam",
    num_neg=50,
    seed=123,
    early_stopping = {'min_delta':0.0, 'patience':5}
)

# RandomSearch
rs_neumf = RandomSearch(
    model = neumf,
    space=[
        Discrete("num_epochs", [50, 100, 150, 200]),
        Discrete("num_factors", [4, 8]),
        Discrete("batch_size", [128, 256, 512]),
        Continuous("lr", 0.001, 0.01)
    ],
    metric = fm,
    eval_method = ratio_split
)

# Put everything together into an experiment and run it
cornac.Experiment(
    eval_method=ratio_split,
    models=[rs_neumf],
    metrics=[ndcg, pre, rec, fm],
).run()

print('Random search: ', rs_neumf.best_params)

ratio_split = RatioSplit(
    data=data,
    test_size=0,
    rating_threshold=1.0,
    verbose=True,
)

neumf = cornac.models.NeuMF(
    num_factors = rs_neumf.best_params['num_factors'],
    layers=[64, 32, 16, 8],
    act_fn="tanh",
    learner="adam",
    num_epochs = rs_neumf.best_params['num_epochs'],
    lr=rs_neumf.best_params['lr'],
    num_neg=50,
    batch_size = rs_neumf.best_params['batch_size'],
    seed=123,
    early_stopping = {'min_delta':0.0, 'patience':5}
)

cornac.Experiment(
    eval_method=ratio_split,
    models=[neumf],
    metrics=[ndcg, pre, rec, fm],
).run()

import pandas as pd
pred_user = pd.read_csv('/content/drive/MyDrive/ML_data/survey_result.csv')
pred_user = set(pred_user['u_id'])

print(data_df.head())

all_prediction = pd.DataFrame(columns=['u_id','p_id','ncf_score'])

for u_idx, u_id in tqdm(enumerate(data_df['userID'].unique())):
    if u_id in pred_user:
        tmp = pd.DataFrame(neumf.rank(u_idx)).T
        tmp['u_id'] = u_id
        tmp = pd.DataFrame(tmp,columns=['u_id',0,1])
        tmp.rename(columns={0:'p_id',1:'ncf_score'}, inplace=True)
        all_prediction = all_prediction.append(tmp)

all_prediction

all_prediction.to_csv('/content/drive/MyDrive/ML_data/predictions/ncf_scores.scv',index=False)

"""CBF 모델"""

import pandas as pd
import numpy as np
import math
# get size of vector
def mag(x):
    return math.sqrt(sum(i**2 for i in x))
res_matrix = pd.read_csv('/content/drive/MyDrive/ML_data/res_matrix.csv')
user_matrix = pd.read_csv('/content/drive/MyDrive/ML_data/user_adj_matrix.csv')
group_count = pd.read_csv('/content/drive/MyDrive/ML_data/group_count.csv',names=['group','count'])

res_matrix.set_index('p_id', drop=True, inplace=True)
user_matrix.set_index('u_id', drop=True, inplace=True)
group_count.set_index('group', drop=True, inplace=True)
user_matrix

"""최종"""
